language: ruby
rbenv:
- 2.5.3
notifications:
  email:
    on_success: never
    on_failure: never
addons:
  postgresql: 9.6
cache:
- bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: yeABuv30MVPy1Co84Vj+7ekImKyFvej06iifSHwJ9zAv/1sPM/Ql6NIx/UbzkP4gDa9rhvlSxWY+93j/miSvubj6G8x/AF38uSX3fhLkEWEKpQ1DaGWZvNgkrvWlMCwNHs+40X/UBTAfP2XzqC8NmUH9AaFlHX8NV4LYafUS0j4jMnZCfeCkyC5vx9w8MAVHBLqhAveQxslBiq1I+1eFpFh9oT9uyzONheloYepGCkPa+9KlPCHoBHcHTC7A80WJz31UGEuPvYfpDgthbiZLWZRtXpe7vFTLjb+Ee5ZUWU6+uXsdFNkvkT0MI+FLh6wC6W5RpXKUzf7sJj6oEw24DBKur0Tu58WWtrOicbgKt5Jfk6EGSm0nxbOOOL+8gcxvsFsZOPBDsaAUl3V/vMoEE7nxr6Cdiwut7EEmRxVFGgIXZBOqvaV/X1xrl772JyZgmrf306sB1p3aT71hV5fCT0RwSxTM3aFcp/hHyPMZu/upVo4KQtgT8wBhgk55pHKgrYT0I+s8KK/SmmCwRHlW8nTap4wM1kd/Xt/PqF7+UT7T4aWh3dUQPe3VWGWUdpe8498jzRUv7BJV8SfXZBfA1byr0HkCbMM7jhJoQMx6bCtj74h/v/MIsrQYJAypb5b9TlS2JglNA9rdYDv/6GaLHByvB53HXOKgwwiCzuSEuo8=
  app: classroom-wars
  on:
    repo: Classroom-Wars/Front-End
  skip_cleanup: 'true'
env:
  global:
    secure: eaxVN1kJ1lndQZ5UGoe7sYPmI7DnKFE3Yb+ZdRWww0f7l6nxS/pb6gJ80Dm9x1ss+J7MGWMWxibpkt3dkt5EN6Z2zG9rCbIvRpayiBieXXNtD94ryxwrN/bUGd+8klFbY+MPVucdXOb4FojmKWRHrmMyoAtGg3C4ukUVSSzRuKLaCYjJnOMwkfPHIPi2/C6l3kRbcHi8vYJmdhBtdT8/uZUbtWO89QVSV963ehppDM7gd4DNGArB8s+t9JJ/gyam4wtqwtWgqhxoDoaibwVMg6wQQe4VBiG2yuDyIGKnRGEaiJ9e3Vjk1YGPl6pcWlphqpTbxep8N5DvEcIx5HkuwYvGbl5wTjfZWkhSA+Swep8DmN5470BW/QnOu/pVNiNvbARLLGQxYx2Er58thes0qUnI3vL+fekRigSY8Z/Ak40AK8p7bHHPmQiO07cRGUhnU4iJ+fFJkszHTQlr9iS6bsbY4BacfluqYOFoiK41TEmuBTDIsXUQqcoVH0hCwBdjgxH8GSoVXoTgeSbSlWbEEJdIRo61qhyfFE+XuPtFMkk1MTzdib5J8nY9/CPbUNxEAcxLfnQG1RrzzaMxScgPBkC7CrSE+M1NEX4kKJmYtMjxPsq6BC9qWpXEV+nB1puON6+3BOvp81whoL56zbC0AMR7rV6VjfTydcc/AXPKTQE=
